import { NodeConnectionTypes, type INodeType, type INodeTypeDescription } from 'n8n-workflow';


export class AzureMediaservicesAssetsandassetfilters implements INodeType {
        description: INodeTypeDescription = {
                displayName: 'Azure Mediaservices Assetsandassetfilters',
                name: 'N8nDevAzureMediaservicesAssetsandassetfilters',
                icon: { light: 'file:./azure-mediaservices-assetsandassetfilters.png', dark: 'file:./azure-mediaservices-assetsandassetfilters.dark.png' },
                group: ['input'],
                version: 1,
                subtitle: '={{\$parameter["operation"] + ": " + \$parameter["resource"]}}',
                description: 'Swagger generated by API Framework.',
                defaults: { name: 'Azure Mediaservices Assetsandassetfilters' },
                usableAsTool: true,
                inputs: [NodeConnectionTypes.Main],
                outputs: [NodeConnectionTypes.Main],
                credentials: [
                        {
                                name: 'N8nDevAzureMediaservicesAssetsandassetfiltersApi',
                                required: true,
                        },
                ],
                requestDefaults: {
                        baseURL: '={{\$credentials.url}}',
                        headers: {
                                Accept: 'application/json',
                                'Content-Type': 'application/json',
                        },
                },
                properties: [
		{
			"displayName": "Resource",
			"name": "resource",
			"type": "options",
			"noDataExpression": true,
			"options": [],
			"default": ""
		},
		
                ],
        };
}
